version: '3'

silent: true

tasks:

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo build

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo clippy --workspace --all-targets

  doc:
    desc: Generates documentation with private items
    cmds:
      - cmd: cargo doc --no-deps --document-private-items

  doc-open:
    desc: Generates documentation with private items and opens it in browser
    cmds:
      - cmd: cargo doc --no-deps --open --document-private-items

  fmt:
    desc: Runs code formatter
    cmds:
      - cmd: cargo fmt

  musl:
    desc: Builds the Linux MUSL target
    cmds:
      - cmd: cargo +stable build --release --target=x86_64-unknown-linux-musl

  release:
    desc: Builds in release mode
    cmds:
      - cmd: cargo +stable build --release

  run:
    desc: Runs the server in release mode
    cmds:
      - cmd: cargo +stable run --release

  run-musl:
    desc: Runs the server in release mode and musl target
    cmds:
      - cmd: cargo +stable run --release --target=x86_64-unknown-linux-musl

  test:
    desc: Runs tests in debug mode
    cmds:
      - cmd: cargo test